boost_include = /home/mvgrass/boost_1_57_0/install-dir/include
boost_lib = /home/mvgrass/boost_1_57_0/install-dir/lib

all:
	g++ linux.cpp -lboost_system -lboost_filesystem -I$(boost_include) -L$(boost_lib) -std=c++11 -o mvgrass
